@startuml sequence
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
hide footbox

skinparam sequence {
ArrowColor #0071B5
ArrowFontName Open Sans
LifeLineBorderColor #0071B5

ParticipantBorderColor #0071B5
ParticipantBackgroundColor #0071B5
ParticipantFontName Open Sans
ParticipantFontSize 17
ParticipantFontColor #EEEEEE
}

"PLC Device" -> Gateway: SSDP Discover: M-SEARCH
Gateway -> "PLC Device": SSDP Response
|||
"PLC Device" -> Gateway: HTTP Get http://[LOCATION from SSDP]
Gateway -> "PLC Device": HTTP Response with UPnP Description XML
|||
"PLC Device" -> Gateway: SOAP Action: GetSupportedDataModels
Gateway -> "PLC Device": SOAP Action Response
|||
"PLC Device" -> Gateway: SOAP Action: GetSupportedParameters
Gateway -> "PLC Device": SOAP Action Response
|||
"PLC Device" -> Gateway: SOAP Action: GetValues
Gateway -> "PLC Device": SOAP Action Response
@enduml
